import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Glenify Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark h-full antialiased`}>
      <body className="min-h-full font-poppins flex flex-col bg-[#0b0f18] text-foreground">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
